version: 2

sources:
  - name: test
    description: "Test database with films and actors data."
    database: test
    schema: public
    tables:
      - name: dim_address
        description: "List of customers."
      - name: dim_customer
        description: "Dimension table with customer information."
      - name: dim_date
        description: "Dimension table with date information."
      - name: dim_location
        description: "Dimension table with location details."
      - name: dim_product
        description: "Dimension table with product information."
      - name: fact_sales
        description: "Fact table with transactional (sales) data."